---
#
# https://www.raspberrypi.org/documentation/installation/installing-images/linux.md
# https://raspberrypi.stackexchange.com/a/99531/31668
# https://raspberrypi.stackexchange.com/questions/37920/how-do-i-set-up-networking-wifi-static-ip-address
#
# ansible-playbook -i inventory/kubeberry.ini -e device=/dev/sdb2 init_microsd_cards.yml
#
- hosts: localhost
  gather_facts: no

  roles:
    - raspbian


