---
- name: raspbian - Gets loop device
  shell: losetup --show -fP "{{ raspbian_img_file }}"
  register: reg_losetup
  become: yes

- name: raspbian - Sets variable 'loop_device' to '{{ reg_losetup.stdout }}'
  set_fact:
    loop_device: "{{ reg_losetup.stdout }}"

- name: raspbian - Mounts 'root' partition '{{ loop_device }}p2' to '{{ raspbian_img_tmp_dir }}'
  mount:
    path: "{{ raspbian_img_tmp_dir }}"
    src: "{{ loop_device }}p2"
    fstype: ext4
    state: mounted
  become: yes

- name: raspbian - Mounts 'boot' partition '{{ loop_device }}p1' to '{{ raspbian_img_tmp_dir }}/boot'
  mount:
    path: "{{ raspbian_img_tmp_dir }}/boot"
    src: "{{ loop_device }}p1"
    fstype: vfat
    state: mounted
  become: yes