---
- name: raspbian - Prompts to insert micro sd card
  pause:
    prompt: "Insert Micro SD Card for '{{ node }}'"

- import_tasks: mount_image_partitions.yml

- name: raspbian - Enables Ssh (by touching '{{ raspbian_img_tmp_dir }}/boot/ssh') for node '{{ node }}'
  file:
    path: "{{ raspbian_img_tmp_dir }}/boot/ssh"
    state: touch
  become: yes

- name: raspbian - Configures '{{ raspbian_img_tmp_dir }}/etc/dhcpcd.conf' for node '{{ node }}'
  blockinfile:
    path: "{{ raspbian_img_tmp_dir }}/etc/dhcpcd.conf"
    block: |
      interface eth0
      static ip_address={{ hostvars[node]['ansible_host'] }}/24
  become: yes

- name: Unmount 'boot' partition '{{ raspbian_img_tmp_dir }}/boot'
  mount:
    path: "{{ raspbian_img_tmp_dir }}/boot"
    src: "{{ loop_device }}p1"
    fstype: vfat
    state: unmounted
  become: yes

- name: Unmount 'root' partition '{{ raspbian_img_tmp_dir }}'
  mount:
    path: "{{ raspbian_img_tmp_dir }}"
    src: "{{ loop_device }}p2"
    fstype: ext4
    state: unmounted
  become: yes

- name: Copies '{{ raspbian_img_file }}' to '{{ device }}'
  shell: |
    dd bs=4M if={{ raspbian_img_file }} of={{ device }} conv=fsync
  become: yes

- name: raspbian - Prompts to eject micro sd card
  pause:
    prompt: "Eject Micro SD Card for '{{ node }}'"
